const app=document.querySelector("#app");let banco=null,etapa=-1,questao=0,respostas={},participante="",serie="",turma="",inicio=null;
async function carregar(){try{const r=await fetch("dados/cenarios.json");banco=await r.json();renderIdentificacao()}catch(e){app.innerHTML='<section class="hero"><h1>Não foi possível carregar os dados.</h1><p>Verifique a publicação do GitHub Pages.</p></section>'}}
function progresso(){const total=banco?.etapas?.length||6;const pct=etapa<0?0:Math.round(((etapa+(questao/banco.etapas[etapa].questoes.length))/total)*100);document.querySelector("#progressText").textContent=etapa<0?"Identificação":`S${21+etapa} • Questão ${questao+1} de ${banco.etapas[etapa].questoes.length}`;document.querySelector("#progressBar").style.width=pct+"%"}
function renderIdentificacao(){progresso();app.innerHTML=`<section class="hero"><span class="eyebrow">4º Bimestre • Gestão de Pessoas</span><h1>Simulador de Gestão de Desempenho</h1><p>Você assumirá o papel de gestor. Sua tarefa é avaliar evidências, tomar decisões e construir ações de desenvolvimento para um colaborador.</p><div class="grid"><div class="card"><span class="tag">Caso</span><h3>${banco.colaborador.nome}</h3><p>${banco.colaborador.cargo} • ${banco.colaborador.tempoEmpresa}</p></div><div class="card"><span class="tag">Percurso</span><h3>S21 → S26</h3><p>Avaliação, métodos, competências, metas, liderança e engajamento.</p></div><div class="card"><span class="tag">Critério</span><h3>Decisão com evidências</h3><p>Leia as situações antes de escolher. O objetivo é aplicar conceitos, não apenas memorizar definições.</p></div></div><div class="card" style="margin-top:20px"><h3>Identificação do participante</h3><div class="field"><label for="nome">Nome fictício ou identificação pedagógica</label><input id="nome" placeholder="Ex.: Estudante 01"></div><div class="grid"><div class="field"><label for="serie">Série</label><select id="serie"><option>2ª série – Ensino Médio</option><option>3ª série – Ensino Médio</option></select></div><div class="field"><label for="turma">Turma</label><input id="turma" placeholder="Ex.: 2º AT – Administração"></div></div></div><div class="actions"><span class="muted">Os dados do caso são fictícios.</span><button class="btn primary" onclick="iniciar()">Iniciar missão →</button></div></section>`}
function iniciar(){participante=document.querySelector("#nome").value.trim()||"Participante não identificado";serie=document.querySelector("#serie").value;turma=document.querySelector("#turma").value.trim()||"Não informada";etapa=0;questao=0;respostas={};inicio=Date.now();renderQuestao()}
function renderQuestao(){progresso();const e=banco.etapas[etapa],q=e.questoes[questao],key=q.id,sel=respostas[key];app.innerHTML=`<section class="hero"><div class="stage-head"><div><span class="eyebrow">${e.codigo} • ${e.titulo}</span><h1>${e.titulo}</h1><p>${e.descricao}</p></div><span class="tag">Questão ${questao+1}/${e.questoes.length}</span></div><div class="card question"><div class="question-number">Decisão gerencial</div><h3>${q.pergunta}</h3>${q.opcoes.map(o=>`<label class="choice ${sel===o[0]?"selected":""}"><input type="radio" name="resp" value="${o[0]}" ${sel===o[0]?"checked":""} onchange="selecionar('${key}','${o[0]}')"> <strong>${o[0].toUpperCase()}.</strong> ${o[1]}</label>`).join("")}</div><div class="notice"><strong>Dica:</strong> procure no enunciado a evidência que justifica a decisão. Em situações reais, uma boa avaliação precisa de critérios e acompanhamento.</div><div class="actions"><button class="btn secondary" onclick="voltar()" ${etapa===0&&questao===0?"disabled":""}>← Voltar</button><button class="btn primary" onclick="avancar()">${etapa===banco.etapas.length-1&&questao===e.questoes.length-1?"Finalizar missão":"Continuar →"}</button></div></section>`}
function selecionar(k,v){respostas[k]=v;renderQuestao()}
function voltar(){if(questao>0){questao--}else if(etapa>0){etapa--;questao=banco.etapas[etapa].questoes.length-1}else{return}renderQuestao()}
function avancar(){const q=banco.etapas[etapa].questoes[questao];if(!respostas[q.id]){alert("Selecione uma alternativa antes de continuar.");return}if(questao<banco.etapas[etapa].questoes.length-1){questao++;renderQuestao()}else if(etapa<banco.etapas.length-1){etapa++;questao=0;renderQuestao()}else renderFinal()}
function calcular(){let total=0,max=0,porEtapa={};banco.etapas.forEach(e=>{let ac=0;e.questoes.forEach(q=>{max++;if(respostas[q.id]===q.opcoes.find(o=>o[2]===1)?.[0]){total++;ac++}});porEtapa[e.codigo]={acertos:ac,total:e.questoes.length,nota:Math.round(ac/e.questoes.length*100)}});return{total,max,nota:Math.round(total/max*100),porEtapa}}
function gerarRelatorio(){const s=calcular(),c=banco.colaborador;return `SIMULADOR DE GESTÃO DE DESEMPENHO\n\nParticipante: ${participante}\nSérie: ${serie}\nTurma: ${turma}\nColaborador: ${c.nome}\nCargo: ${c.cargo}\nTempo de empresa: ${c.tempoEmpresa}\n\nRESULTADO\nAcertos: ${s.total}/${s.max}\nDesempenho: ${s.nota}/100\nTempo de realização: ${Math.round((Date.now()-inicio)/60000)} min\n\nDESEMPENHO POR CONTEÚDO\n${Object.entries(s.porEtapa).map(([k,v])=>`${k}: ${v.acertos}/${v.total} (${v.nota}/100)`).join("\n")}\n\nFOCOS DO CASO\nPontos fortes: ${c.pontosFortes.join(", ")}\nDesenvolvimento: ${c.desenvolvimento.join(", ")}\n\nGerado em: ${new Date().toLocaleString("pt-BR")}`}
function salvarResultado(){const s=calcular();const r={data:new Date().toISOString(),participante,serie,turma,colaborador:banco.colaborador.nome,total:s.total,max:s.max,nota:s.nota,...Object.fromEntries(Object.entries(s.porEtapa).map(([k,v])=>[`nota_${k}`,v.nota]))};const lista=JSON.parse(localStorage.getItem("desempenho_resultados")||"[]");lista.push(r);localStorage.setItem("desempenho_resultados",JSON.stringify(lista))}
function renderFinal(){progresso();salvarResultado();const s=calcular(),c=banco.colaborador;app.innerHTML=`<section class="hero"><span class="eyebrow">Missão concluída</span><h1>Parecer gerencial</h1><div class="score"><div class="score-ring" style="--score:${s.nota*3.6}deg"><b>${s.nota}</b></div><div><div class="metric">${s.total}/${s.max}</div><div class="muted">decisões corretas</div></div></div><div class="grid">${Object.entries(s.porEtapa).map(([k,v])=>`<div class="card"><span class="tag">${k}</span><h3>${v.acertos}/${v.total}</h3><p class="muted">${v.nota}/100</p></div>`).join("")}</div><div class="notice"><strong>Leitura pedagógica:</strong> o resultado mostra em quais conteúdos você aplicou melhor os conceitos. Use os pontos com menor desempenho para orientar sua revisão.</div><h3>Relatório da simulação</h3><pre class="report">${gerarRelatorio()}</pre><div class="actions"><button class="btn secondary" onclick="baixar()">Baixar relatório</button><button class="btn primary" onclick="renderIdentificacao()">Nova simulação</button></div></section>`}
function baixar(){const blob=new Blob([gerarRelatorio()],{type:"text/plain;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="relatorio-gestao-desempenho.txt";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
carregar();