const STORE="desempenho_resultados";
const ETAPAS=["S21","S22","S23","S24","S25","S26"];
const CODIGO_ACESSO_PROFESSOR="131313";
function acessarPainel(event){event?.preventDefault();const entrada=document.querySelector("#codigoAcesso");if(entrada.value!==CODIGO_ACESSO_PROFESSOR){document.querySelector("#erroAcesso").textContent="Código incorreto. Confira e tente novamente.";entrada.value="";entrada.focus();return false}document.querySelector("#acessoProfessor").hidden=true;document.querySelector("#painelProfessor").hidden=false;render();return false}
function registros(){try{const x=JSON.parse(localStorage.getItem(STORE)||"[]");return Array.isArray(x)?x.map((r,i)=>({...r,id:r.id||`legado-${r.data||"sem-data"}-${i}`})):[]}catch{return []}}
function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function resumo(){const a=registros(),n=a.length,media=n?Math.round(a.reduce((t,x)=>t+(Number(x.nota)||0),0)/n):0;document.querySelector("#resumo").innerHTML=[[n,"missões concluídas"],[media,"média geral / 100"],[new Set(a.map(x=>x.turma)).size,"turmas registradas"]].map(([v,l])=>`<article class="card"><div class="metric">${v}</div><p class="muted">${l}</p></article>`).join("")}
function render(){resumo();const termo=(document.querySelector("#filtro").value||"").toLocaleLowerCase("pt-BR"),a=registros().filter(x=>[x.participante,x.serie,x.turma].join(" ").toLocaleLowerCase("pt-BR").includes(termo)).sort((x,y)=>String(y.data||"").localeCompare(String(x.data||"")));const root=document.querySelector("#resultados");if(!a.length){root.innerHTML='<div class="empty">Nenhum resultado local encontrado. Conclua uma missão neste navegador para preencher o painel.</div>';return}root.innerHTML=`<div class="table-wrap"><table class="table"><thead><tr><th>Participante</th><th>Série/turma</th><th>Data</th><th>Resultado</th>${ETAPAS.map(x=>`<th>${x}</th>`).join("")}<th>Dossiê</th></tr></thead><tbody>${a.map(x=>`<tr><td>${esc(x.participante)}</td><td>${esc(x.serie)} • ${esc(x.turma)}</td><td>${x.data?new Date(x.data).toLocaleDateString("pt-BR"):"—"}</td><td><strong>${Number(x.nota)||0}/100</strong></td>${ETAPAS.map(k=>`<td>${x.porEtapa?.[k]?.nota??x[`nota_${k}`]??"—"}</td>`).join("")}<td><button class="btn secondary small" onclick="ver('${esc(x.id)}')">Abrir</button></td></tr>`).join("")}</tbody></table></div>`}
function ver(id){const x=registros().find(r=>r.id===id);if(!x)return;const box=document.querySelector("#detalhe");box.innerHTML=`<article class="card detail"><h2>Dossiê • ${esc(x.participante)}</h2><p>${esc(x.colaborador)} • ${esc(x.serie)} • ${esc(x.turma)} • ${Number(x.nota)||0}/100</p><h3>Descritores</h3><div class="table-wrap"><table class="table"><tbody>${Object.entries(x.descritores||{}).map(([k,v])=>`<tr><td>${esc(k)}</td><td>${v.pontos}/${v.max}</td></tr>`).join("")}</tbody></table></div><h3>Consequências das decisões</h3><ul>${Object.entries(x.consequencias||{}).map(([k,v])=>`<li><strong>${esc(k)}:</strong> ${esc(v)}</li>`).join("")}</ul><h3>Parecer do gestor</h3><p>${esc(x.dossie||"Não registrado")}</p><h3>Produções</h3><pre class="report">${esc(Object.entries(x.producoes||x.respostas||{}).map(([k,v])=>`${k}: ${v}`).join("\n"))}</pre><button class="btn secondary" onclick="document.querySelector('#detalhe').innerHTML=''">Fechar</button></article>`;box.scrollIntoView({behavior:"smooth",block:"start"})}
function baixar(name,data,type){const a=document.createElement("a"),u=URL.createObjectURL(new Blob([data],{type}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function exportarJSON(){baixar("resultados-simulador-desempenho.json",JSON.stringify(registros(),null,2),"application/json;charset=utf-8")}
function csv(v){return `"${String(v??"").replace(/"/g,'""')}"`}
function exportarCSV(){const a=registros(),headers=["data","participante","serie","turma","colaborador","nota","total_descritores","max_descritores",...ETAPAS.map(k=>`nota_${k}`),"dossie"];const rows=a.map(x=>[x.data,x.participante,x.serie,x.turma,x.colaborador,x.nota,x.total,x.max,...ETAPAS.map(k=>x.porEtapa?.[k]?.nota??x[`nota_${k}`]??""),x.dossie].map(csv).join(";"));baixar("resultados-simulador-desempenho.csv",[headers.join(";"),...rows].join("\r\n"),"text/csv;charset=utf-8")}
function limpar(){if(!registros().length)return;if(confirm("Apagar todos os resultados salvos neste navegador? Exporte uma cópia antes, se precisar.")){localStorage.removeItem(STORE);document.querySelector("#detalhe").innerHTML="";render()}}
