const API_URL="https://script.google.com/macros/s/AKfycbwrrIUSuthv0W1t0mZjFlctC0fQHWAQ5A8OLwLilbRrDp3om71PUax7vcAe3cOBBk06/exec";
const S={step:0,student:"",serie:"",turma:"",c:[],allCandidates:[],participants:[],tri:[],cha:{},final:[],hire:"",train:"",answers:{},why:"",submissionId:""};
const A=document.querySelector("#app");
const steps=["Briefing","Recrutamento","Triagem","CHA","Teste","Entrevista","Decisão","Desenvolvimento","Resultado"];
let bank={},testBank=[];
async function boot(){S.allCandidates=(await (await fetch("dados/candidatos.json")).json()).candidatos;const dadosParticipantes=(await (await fetch("dados/participantes.json")).json());S.participants=dadosParticipantes.participantes;bank=await (await fetch("dados/avaliacao.json")).json();testBank=await (await fetch("dados/teste.json")).json();const serie=document.querySelector("#serie");const turma=document.querySelector("#class");const sel=document.querySelector("#student");sel.innerHTML="<option value=\"\">Selecione o seu nome</option>"+S.participants.map(function(n){return "<option value=\""+esc(n)+"\">"+esc(n)+"</option>"}).join("");function atualizarTurmas(){const ano=serie.value;turma.innerHTML="<option value=\"\">Selecione a turma</option>";turma.disabled=!ano;let opcoes=ano==="2º ano do Ensino Médio"?["2º AT – Administração","2º BT – Administração"]:ano==="3º ano do Ensino Médio"?["3º AT – Administração"]:[];turma.innerHTML="<option value=\"\">Selecione a turma</option>"+opcoes.map(function(t){return "<option value=\""+t+"\">"+t+"</option>"}).join("");S.turma="";}serie.addEventListener("change",atualizarTurmas);atualizarTurmas();document.querySelector("#start").onclick=start}
function embaralhar(a){return a.slice().sort(function(){return Math.random()-0.5})}
function sortearCandidatos(){var o=S.allCandidates.slice().sort(function(a,b){return fit(b)-fit(a)});var g=[o.slice(0,8),o.slice(8,16),o.slice(16,24),o.slice(24)];var s=[];[4,6,6,4].forEach(function(n,i){s=s.concat(embaralhar(g[i]).slice(0,n))});S.c=embaralhar(s)}
function start(){S.student=document.querySelector("#student").value.trim();S.serie=document.querySelector("#serie").value;S.turma=document.querySelector("#class").value;if(!S.student){alert("Selecione o seu nome corretamente.");document.querySelector("#student").focus();return}if(!S.serie){alert("Selecione a série.");return}if(!S.turma){alert("Selecione a turma.");return}sortearCandidatos();S.step=1;render()}
function nav(){return "<p>"+steps.map(function(x,i){return "<span class='tag'>"+(i+1)+". "+x+"</span>"}).join("")+"</p>"}
function render(){A.innerHTML=nav()+views[S.step]();window.scrollTo(0,0)}
function esc(s){return String(s).replace(/</g,"&lt;").replace(/>/g,"&gt;")}
function questionBlock(group){return "<div class='quiz'>"+bank[group].map(function(q,i){return "<div class='notice'><b>"+q.q+"</b>"+q.opts.map(function(o,j){return "<label><input type='radio' name='"+group+i+"' value='"+j+"'> "+o+"</label>"}).join("")+"</div>"}).join("")+"</div>"}
function gradeGroup(group){let total=0,ok=0;bank[group].forEach(function(q,i){let el=document.querySelector("input[name='"+group+i+"']:checked");if(el){total++;if(Number(el.value)===q.a)ok++}});S.answers[group]={ok:ok,total:bank[group].length};return ok}
function fit(c){var h=["excel","word","google","atendimento","organização","organizacao","documentos","erp","indicadores","planilhas","dados","relatórios","relatorios","sistemas"];var so=["comunicação","comunicacao","organização","organizacao","equipe","responsabilidade","empatia","resolução","resolucao","adaptabilidade","colaboração","colaboracao"];var hm=c.hard.filter(function(x){return h.some(function(k){return x.toLowerCase().includes(k)})}).length;var sm=c.soft.filter(function(x){return so.some(function(k){return x.toLowerCase().includes(k)})}).length;var meses=0;var mAno=String(c.experiencia||"").match(/(\d+)\s+ano/);var mMes=String(c.experiencia||"").match(/(\d+)\s+mes/);if(mAno)meses+=Number(mAno[1])*12;if(mMes)meses+=Number(mMes[1]);var ex=meses>=13?90:75;var fo=/Técnico em Administração/.test(c.formacao)?(/em andamento/i.test(c.formacao)?85:95):/Tecnólogo/.test(c.formacao)?90:75;var hs=c.hard.length?Math.min(100,hm/c.hard.length*100):0;var ss=c.soft.length?Math.min(100,sm/c.soft.length*100):0;return Math.round(hs*.30+ss*.30+ex*.20+fo*.10+c.entrevista*.10)}
function fotoUrl(c){return "/aulas/simulador-rh-mvp/assets/candidatos/"+encodeURIComponent(c.foto||"")}
function salarioStatus(c){var n=Number(String(c.pretensao).replace(/[^0-9,.-]/g,"").replace(".","").replace(",","."));if(!isFinite(n))return "Não informado";if(n<2200)return "Abaixo da faixa";if(n<=2400)return "Dentro da faixa";return "Acima da faixa"}
function card(c){return "<article class='candidate "+(S.tri.includes(c.id)?"selected":"")+"'><img class='candidate-photo' src='"+fotoUrl(c)+"' alt='Foto ilustrativa de "+esc(c.nome)+"' loading='lazy' onerror='this.style.display=\"none\"'><div class='avatar'>"+c.nome.split(" ").slice(0,2).map(function(x){return x[0]}).join("")+"</div><div class='candidate-id'>"+c.id+"</div><b>"+esc(c.nome)+"</b><p>"+esc(c.formacao)+"</p><p>"+esc(c.experiencia)+"</p><p>"+c.hard.slice(0,3).map(function(x){return "<span class='tag'>"+esc(x)+"</span>"}).join("")+"</p><details><summary>Ver ficha completa</summary><p><b>Hard skills:</b> "+c.hard.map(esc).join(", ")+"</p><p><b>Soft skills:</b> "+c.soft.map(esc).join(", ")+"</p><p><b>Teste:</b> "+c.teste+"/100 • <b>Entrevista:</b> "+c.entrevista+"/100</p><p><b>Pretensão:</b> R$ "+c.pretensao+" • <b>Faixa da vaga:</b> R$ 2.200–R$ 2.400 • <b>Compatibilidade salarial:</b> "+salarioStatus(c)+" • <b>Disponibilidade:</b> "+esc(c.disponibilidade)+"</p><p><b>Desenvolvimento:</b> "+esc(c.desenvolvimento)+"</p></details><button onclick='tri(\""+c.id+"\")'>"+(S.tri.includes(c.id)?"Retirar":"Selecionar")+"</button></article>"}
const views=[
function(){return ""},
function(){return "<section class='card'><small>MISSÃO</small><h1>Processo seletivo: Assistente Administrativo</h1><p>A Nova Gestão Serviços Administrativos Ltda. (simulada) precisa contratar um profissional para apoiar documentos, atendimento, planilhas e controles internos.</p><div class='notice'><b>Remuneração oferecida:</b> R$ 2.200 a R$ 2.400 mensais.<br><b>Requisitos:</b> ensino médio, informática básica, organização, comunicação e trabalho em equipe.<br><b>Diferenciais:</b> Excel intermediário, experiência administrativa, ERP e indicadores.<br><b>Critério de análise:</b> a pretensão salarial deve ser considerada junto às demais evidências do processo; não elimine automaticamente um candidato apenas por esse fator.</div><h2>Seu papel</h2><p>Você será responsável por tomar decisões em diferentes etapas. Suas escolhas serão analisadas pelo processo, não apenas pelo resultado final.</p><button onclick='go(2)'>Começar recrutamento</button></section>"},
function(){return "<section class='card'><h1>Etapa 2 — Recrutamento</h1><p>Antes de analisar currículos, responda às questões sobre recrutamento e seleção.</p>"+questionBlock("recrutamento")+"<button onclick='finishRecruitment()'>Continuar</button></section>"},
function(){return "<section class='card'><h1>Etapa 3 — Triagem curricular</h1><p>Você recebeu <b>20 candidatos</b> para análise. O sistema sorteou este conjunto de forma controlada. Selecione até <b>8 candidatos</b> para a próxima etapa. A fotografia é apenas identificação visual; utilize as informações profissionais.</p><div class='grid'>"+S.c.map(card).join("")+"</div><p><b>"+S.tri.length+"/8 selecionados</b></p><button onclick='go(4)' "+(S.tri.length<3?"disabled":"")+">Continuar para CHA</button></section>"},
function(){return "<section class='card'><h1>Etapa 4 — Modelo CHA</h1><p>Associe competências técnicas e socioemocionais aos candidatos selecionados. Depois responda ao miniquestionário.</p>"+S.tri.map(function(id){let c=S.c.find(function(x){return x.id===id});return "<div class='notice'><b>"+c.nome+"</b><label>Hard skill<select onchange=\"setcha('"+id+"','h',this.value)\"><option value=''>Selecione</option>"+c.hard.map(function(x){return "<option>"+esc(x)+"</option>"}).join("")+"</select></label><label>Soft skill<select onchange=\"setcha('"+id+"','s',this.value)\"><option value=''>Selecione</option>"+c.soft.map(function(x){return "<option>"+esc(x)+"</option>"}).join("")+"</select></label></div>"}).join("")+"<h2>Verificação</h2>"+questionBlock("cha")+"<button onclick='finishCHA()'>Continuar para teste</button></section>"},
function(){return "<section class='card'><h1>Etapa 5 — Teste técnico</h1><p>Resolva as situações práticas. Aqui, conhecimento técnico e comportamento aparecem juntos, mas devem ser distinguidos.</p><div class='quiz'>"+testBank.map(function(q,i){return "<div class='notice'><b>"+q.q+"</b>"+q.opts.map(function(o,j){return "<label><input type='radio' name='teste"+i+"' value='"+j+"'> "+o+"</label>"}).join("")+"</div>"}).join("")+"</div><button onclick='finishTest()'>Ver resultados e entrevistas</button></section>"},
function(){return "<section class='card'><h1>Etapa 6 — Entrevista</h1><p>Você recebeu os resultados das etapas anteriores. Compare evidências, mas não reduza a seleção a um único indicador.</p><table><tr><th>Candidato</th><th>Teste</th><th>Entrevista</th><th>Desenvolvimento</th></tr>"+S.tri.map(function(id){let c=S.c.find(function(x){return x.id===id});return "<tr><td>"+esc(c.nome)+"</td><td>"+c.teste+"/100</td><td>"+c.entrevista+"/100</td><td>"+esc(c.desenvolvimento)+"</td></tr>"}).join("")+"</table><h3>Pergunta de análise</h3><p>Na comparação final entre os candidatos, quais evidências devem ser consideradas em conjunto para tomar uma decisão de seleção?</p><select id='evidence'><option value=''>Selecione</option><option value='integrated'>Competências técnicas e socioemocionais, desempenho no teste, experiência e evidências da entrevista, considerando os requisitos da vaga</option><option value='technical'>Apenas o resultado do teste técnico</option><option value='experience'>Apenas o tempo de experiência profissional</option><option value='single'>Apenas o maior número obtido em uma etapa</option></select><br><br><button onclick='finishInterview()'>Ir para decisão</button></section>"},
function(){return "<section class='card'><h1>Etapa 7 — Decisão final</h1><p><b>Você agora atua como responsável pelo processo seletivo.</b> Escolha até 3 finalistas e indique quem seria contratado. <div class='notice'><b>Importante:</b> sua decisão será apresentada ao RH da empresa. A justificativa é parte importante da avaliação. Fundamente sua escolha com evidências do processo seletivo.</div></p><div class='grid'>"+S.tri.map(function(id){let c=S.c.find(function(x){return x.id===id});return "<article class='candidate "+(S.final.includes(id)?"selected":"")+"'><img class='candidate-photo small' src='"+fotoUrl(c)+"' alt='Foto ilustrativa de "+esc(c.nome)+"' loading='lazy' onerror='this.style.display=\"none\"'><b>"+esc(c.nome)+"</b><p>Teste: "+c.teste+" • Entrevista: "+c.entrevista+" • Pretensão: R$ "+c.pretensao+" • Salário: "+salarioStatus(c)+"</p><button onclick=\"fin('"+id+"')\">"+(S.final.includes(id)?"Retirar":"Finalista")+"</button></article>"}).join("")+"</div><label>Contratado<select id='hire'><option value=''>Selecione</option>"+S.final.map(function(id){let c=S.c.find(function(x){return x.id===id});return "<option value='"+id+"'>"+esc(c.nome)+"</option>"}).join("")+"</select></label><label><b>Justificativa profissional</b><textarea id='why' rows='8' placeholder='O candidato foi selecionado para a vaga de Assistente Administrativo por atender aos requisitos necessários para sua contratação pelos seguintes motivos...'></textarea><small>Use evidências de formação, experiência, hard skills, soft skills, teste, entrevista, requisitos da vaga e, quando pertinente, compatibilidade salarial.</small></label><button onclick='decision()'>Confirmar decisão</button></section>"},
function(){let c=S.c.find(function(x){return x.id===S.hire});return "<section class='card'><h1>Etapa 8 — Treinamento e desenvolvimento</h1><div class='notice'><b>"+esc(c.nome)+"</b><br>Necessidade identificada: "+esc(c.desenvolvimento)+"</div><p>Escolha a modalidade mais adequada e responda ao bloco de desenvolvimento.</p><div class='grid'>"+["Presencial","Online","Híbrido","Prático no trabalho"].map(function(x){return "<button onclick=\"train('"+x+"')\">"+x+"</button>"}).join("")+"</div>"+questionBlock("desenvolvimento")+"<br><button onclick='finishDevelopment()'>Concluir processo</button></section>"},
function(){let c=S.c.find(function(x){return x.id===S.hire});let filled=Object.values(S.cha).filter(function(x){return x.h&&x.s}).length;let scores=calcScores();let just=avaliarJustificativa();let chosenFit=fit(c);let allSorted=S.c.slice().sort(function(a,b){return fit(b)-fit(a)});let best=allSorted[0];let rank=allSorted.findIndex(function(x){return x.id===c.id})+1;let feedback=scores.d1>=70?"Você identificou conceitos centrais do recrutamento e seleção.":"Revise a diferença entre recrutamento, seleção e instrumentos de avaliação.";let feedback2=scores.d2>=70?"Você conseguiu relacionar competências técnicas e socioemocionais às evidências.":"Revise a distinção entre hard skills e soft skills e observe as evidências antes de decidir.";let feedback3=scores.d3>=70?"Você relacionou necessidade de desenvolvimento e modalidade de treinamento.":"Revise a relação entre lacuna de competência, necessidade de treinamento e modalidade.";return "<section class='card'><small>DEVOLUTIVA PEDAGÓGICA</small><h1>Processo concluído</h1><p><b>Participante:</b> "+esc(S.student)+" • <b>Série:</b> "+esc(S.serie)+" • <b>Turma:</b> "+esc(S.turma)+"</p><div class='grid'><div class='notice'><div class='score'>"+scores.d1+"%</div><b>Descritor 1</b><br>Recrutamento e seleção</div><div class='notice'><div class='score'>"+scores.d2+"%</div><b>Descritor 2</b><br>CHA</div><div class='notice'><div class='score'>"+scores.d3+"%</div><b>Descritor 3</b><br>Treinamento e desenvolvimento</div></div><h2>Decisão registrada</h2><p><b>"+esc(c.nome)+"</b></p><p>Treinamento: <b>"+esc(S.train)+"</b></p><div class='notice'><b>Justificativa profissional:</b><br>"+esc(S.why)+"<br><br><b>Avaliação da justificativa:</b> "+just.pontos+"/7</div><h3>Feedback</h3><div class='notice'>"+feedback+"<br><br>"+feedback2+"<br><br>"+feedback3+"</div><p><b>Triagem:</b> "+S.tri.length+" • <b>CHA preenchido:</b> "+filled+"/"+S.tri.length+"</p><div class='notice'><b>Compatibilidade objetiva:</b> "+chosenFit+"/100.<br><b>Compatibilidade salarial do contratado:</b> "+salarioStatus(c)+".<br>O perfil com maior alinhamento aos critérios técnicos da vaga foi <b>"+esc(best.nome)+"</b> ("+fit(best)+"/100). Sua escolha ficou na posição <b>"+rank+"ª</b> pela matriz. Isso não substitui sua justificativa: explique a decisão usando evidências do processo.</div><button onclick='exportResult()'>Baixar relatório para abrir/imprimir</button> <button onclick='location.reload()'>Nova simulação</button></section>"}
];
function go(n){S.step=n;render()}
function tri(id){if(S.tri.includes(id))S.tri=S.tri.filter(function(x){return x!==id});else if(S.tri.length<8)S.tri.push(id);render()}
function setcha(id,k,v){if(!S.cha[id])S.cha[id]={};S.cha[id][k]=v}
function fin(id){if(S.final.includes(id))S.final=S.final.filter(function(x){return x!==id});else if(S.final.length<3)S.final.push(id);render()}
function finishRecruitment(){S.answers.recrutamento={ok:gradeGroup("recrutamento")};go(3)}
function finishCHA(){S.answers.chaQuiz={ok:gradeGroup("cha")};go(5)}
function finishTest(){let ok=0;testBank.forEach(function(q,i){let el=document.querySelector("input[name='teste"+i+"']:checked");if(el&&Number(el.value)===q.a)ok++});S.answers.teste={ok:ok,total:testBank.length};go(6)}
function finishInterview(){S.answers.evidence=document.querySelector("#evidence").value;go(7)}
function avaliarJustificativa(){var t=String(S.why||"").toLowerCase(),p=0;if(t.length>=80)p++;if(/requisit|vaga|adequad|perfil/.test(t))p++;if(/excel|word|erp|planilha|sistema|atendimento|document|relatório|relatorio|indicador|processo/.test(t))p++;if(/comunica|equipe|organiza|responsab|empatia|lideran|colabora|proativ|adaptab|negocia/.test(t))p++;if(/teste|entrevista|experiên|experien|desempenho|resultado|pontua/.test(t))p++;if(/salári|salario|pretens|remunera|faixa|orçamento|orcamento/.test(t))p++;if(t.split(/\s+/).filter(Boolean).length>=45)p++;return{pontos:p,max:7}}
function decision(){S.hire=document.querySelector("#hire").value;S.why=document.querySelector("#why").value;if(!S.hire)return alert("Selecione o contratado.");if(S.why.trim().length<40)return alert("Sua justificativa precisa apresentar evidências e argumentação profissional.");go(8)}
function train(x){S.train=x}
function finishDevelopment(){if(!S.train)return alert("Escolha uma modalidade de treinamento.");S.answers.desenvolvimentoQuiz={ok:gradeGroup("desenvolvimento")};salvarResultadoAutomaticamente();go(9)}
function montarResultado(){
let hired=S.c.find(function(x){return x.id===S.hire});
let scores=calcScores();
if(!S.submissionId)S.submissionId=(crypto&&crypto.randomUUID)?crypto.randomUUID():(Date.now()+"-"+Math.random().toString(16).slice(2));
return {id:S.submissionId,participant:S.student,participante:S.student,serie:S.serie,turma:S.turma,final:S.final,finalistas:S.final,hire:S.hire,contratado:S.hire,training:S.train,treinamento:S.train,why:S.why,justificativa:S.why,answers:S.answers,scores:{D1:scores.d1,D2:scores.d2,D3:scores.d3},pontuacao:scores,compatibility:hired?fit(hired):0,compatibilidade:hired?fit(hired):0,timestamp:new Date().toISOString(),data:new Date().toISOString()};
}
async function salvarResultadoAutomaticamente(){
try{
let out=montarResultado();
await fetch(API_URL,{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(out),keepalive:true});
}catch(e){console.warn("Não foi possível registrar automaticamente no REC_RH.",e)}
}
function calcScores(){let r=(S.answers.recrutamento?.ok||0)/3*30;let selected=S.tri.map(function(id){return S.c.find(function(x){return x.id===id})}).filter(Boolean);let triFit=selected.length?selected.reduce(function(sum,c){return sum+fit(c)},0)/selected.length/100*25:0;let evidence=S.answers.evidence==="integrated"?15:0;let just=(avaliarJustificativa().pontos/7)*30;let d1=Math.round(r+triFit+evidence+just);
let cq=(S.answers.chaQuiz?.ok||0)/3*30;let filled=Object.values(S.cha).filter(function(x){return x.h&&x.s}).length;let cha=selected.length?filled/selected.length*20:0;let tq=(S.answers.teste?.ok||0)/testBank.length*30;let d2=Math.round(cq+cha+tq+20);
let dq=(S.answers.desenvolvimentoQuiz?.ok||0)/3*50;let c=S.c.find(function(x){return x.id===S.hire});let need=(c&&c.desenvolvimento||"").toLowerCase();let practical=/(comunicação|atendimento|reuniões|publico|público)/.test(need);let technical=/(excel|erp|sistemas|processos|indicadores|rotinas|relatórios|relatorios)/.test(need);let train=(practical&&(S.train==="Prático no trabalho"||S.train==="Presencial"||S.train==="Híbrido"))||(technical&&(S.train==="Online"||S.train==="Híbrido"||S.train==="Prático no trabalho"))?30:18;let d3=Math.round(dq+train+20);return{d1:Math.min(100,d1),d2:Math.min(100,d2),d3:Math.min(100,d3)}}
function exportResult(){
let hired=S.c.find(function(x){return x.id===S.hire});
let finalists=S.final.map(function(id){return S.c.find(function(x){return x.id===id})}).filter(Boolean);
let scores=calcScores();
let out=montarResultado();
let slug=String(S.student).trim().normalize("NFD").replace(/[\\u0300-\\u036f]/g,"").replace(/\\s+/g,"-").replace(/[^A-Za-z0-9_-]/g,"")||"participante";
let escapeHtml=function(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")};
let answerLabels={integrated:"Competências técnicas e socioemocionais, desempenho no teste, experiência e evidências da entrevista, considerando os requisitos da vaga",technical:"Apenas o resultado do teste técnico",experience:"Apenas o tempo de experiência profissional",single:"Apenas o maior número obtido em uma etapa"};
let evidenceText=answerLabels[S.answers.evidence]||"Não informado";
let finalRows=finalists.map(function(x){return "<tr><td>"+escapeHtml(x.id)+"</td><td>"+escapeHtml(x.nome)+"</td><td>"+x.teste+"/100</td><td>"+x.entrevista+"/100</td><td>"+escapeHtml(x.formacao)+"</td><td>"+escapeHtml(x.experiencia)+"</td></tr>"}).join("");
let html="<!doctype html><html lang='pt-BR'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Relatório RH - "+escapeHtml(S.student)+"</title><style>body{font-family:Arial,sans-serif;margin:40px;color:#172b3a;line-height:1.5}h1{margin-bottom:4px}h2{margin-top:28px;border-bottom:2px solid #ddd;padding-bottom:6px}.meta,.box{background:#f4f7fa;padding:14px;border-radius:8px;margin:12px 0}.scores{display:flex;gap:12px;flex-wrap:wrap}.score{padding:14px 20px;background:#e9f2f8;border-radius:8px;min-width:120px}.score b{font-size:24px;display:block}table{border-collapse:collapse;width:100%;font-size:13px}th,td{border:1px solid #ccc;padding:8px;text-align:left;vertical-align:top}th{background:#eef3f6}.small{color:#667781;font-size:12px}@media print{body{margin:18px}}</style></head><body><h1>Relatório — Simulador RH</h1><div class='meta'><b>Participante:</b> "+escapeHtml(S.student)+"<br><b>Série:</b> "+escapeHtml(S.serie)+"<br><b>Turma:</b> "+escapeHtml(S.turma)+"</div><h2>Resultado pedagógico</h2><div class='scores'><div class='score'><b>"+scores.d1+"%</b>Descritor 1<br>Recrutamento e seleção</div><div class='score'><b>"+scores.d2+"%</b>Descritor 2<br>CHA</div><div class='score'><b>"+scores.d3+"%</b>Descritor 3<br>Treinamento e desenvolvimento</div></div><h2>Decisão registrada</h2><div class='box'><b>Contratado:</b> "+escapeHtml(hired?hired.nome:S.hire)+"<br><b>Treinamento:</b> "+escapeHtml(S.train)+"<br><b>Compatibilidade objetiva:</b> "+(hired?fit(hired):0)+"/100<br><b>Compatibilidade salarial:</b> "+(hired?salarioStatus(hired):"Não informado")+"<br><b>Faixa da vaga:</b> R$ 2.200 a R$ 2.400</div><h2>Finalistas</h2><table><tr><th>ID</th><th>Nome</th><th>Teste</th><th>Entrevista</th><th>Formação</th><th>Experiência</th></tr>"+(finalRows||"<tr><td colspan='6'>Nenhum finalista registrado.</td></tr>")+"</table><h2>Análise</h2><div class='box'><b>Faixa salarial da vaga:</b> R$ 2.200 a R$ 2.400 mensais.<br><b>Compatibilidade salarial do contratado:</b> "+(hired?salarioStatus(hired):"Não informado")+"</div><div class='box'><b>Evidência considerada:</b><br>"+escapeHtml(evidenceText)+"</div><div class='box'><b>Justificativa do estudante:</b><br>"+escapeHtml(S.why||"Não informada.")+"</div><h2>Desempenho nas questões</h2><div class='box'>Recrutamento: "+(S.answers.recrutamento?.ok||0)+"/3<br>CHA — questionário: "+(S.answers.chaQuiz?.ok||0)+"/3<br>Teste técnico: "+(S.answers.teste?.ok||0)+"/"+testBank.length+"<br>Desenvolvimento: "+(S.answers.desenvolvimentoQuiz?.ok||0)+"/3</div><p class='small'>Gerado em "+escapeHtml(new Date(out.data).toLocaleString("pt-BR"))+". Este relatório é uma devolutiva da atividade pedagógica.</p></body></html>";
let htmlBlob=new Blob([html],{type:"text/html;charset=utf-8"});let htmlA=document.createElement("a");htmlA.href=URL.createObjectURL(htmlBlob);htmlA.download="relatorio-"+slug+".html";htmlA.click();setTimeout(function(){URL.revokeObjectURL(htmlA.href)},1000);
let jsonBlob=new Blob([JSON.stringify(out,null,2)],{type:"application/json"});let jsonA=document.createElement("a");jsonA.href=URL.createObjectURL(jsonBlob);jsonA.download="dados-"+slug+".json";jsonA.click();setTimeout(function(){URL.revokeObjectURL(jsonA.href)},1000);
}
boot();