const S={step:0,student:"",turma:"",c:[],tri:[],cha:{},final:[],hire:"",train:"",answers:{},why:""};
const A=document.querySelector("#app");
const steps=["Briefing","Recrutamento","Triagem","CHA","Teste","Entrevista","Decisão","Desenvolvimento","Resultado"];
let bank={},testBank=[];
async function boot(){S.c=(await (await fetch("dados/candidatos.json")).json()).candidatos;bank=await (await fetch("dados/avaliacao.json")).json();testBank=await (await fetch("dados/teste.json")).json();document.querySelector("#start").onclick=start}
function start(){S.student=document.querySelector("#student").value.trim()||"SEM-CODIGO";S.turma=document.querySelector("#class").value;S.step=1;render()}
function nav(){return "<p>"+steps.map(function(x,i){return "<span class='tag'>"+(i+1)+". "+x+"</span>"}).join("")+"</p>"}
function render(){A.innerHTML=nav()+views[S.step]();window.scrollTo(0,0)}
function esc(s){return String(s).replace(/</g,"&lt;").replace(/>/g,"&gt;")}
function questionBlock(group){return "<div class='quiz'>"+bank[group].map(function(q,i){return "<div class='notice'><b>"+q.q+"</b>"+q.opts.map(function(o,j){return "<label><input type='radio' name='"+group+i+"' value='"+j+"'> "+o+"</label>"}).join("")+"</div>"}).join("")+"</div>"}
function gradeGroup(group){let total=0,ok=0;bank[group].forEach(function(q,i){let el=document.querySelector("input[name='"+group+i+"']:checked");if(el){total++;if(Number(el.value)===q.a)ok++}});S.answers[group]={ok:ok,total:bank[group].length};return ok}
function fit(c){var h=["excel","word","google","atendimento","organização","organizacao","documentos","erp","indicadores","planilhas","dados","relatórios","relatorios","sistemas"];var so=["comunicação","comunicacao","organização","organizacao","equipe","responsabilidade","empatia","resolução","resolucao","adaptabilidade","colaboração","colaboracao"];var hm=c.hard.filter(function(x){return h.some(function(k){return x.toLowerCase().includes(k)})}).length;var sm=c.soft.filter(function(x){return so.some(function(k){return x.toLowerCase().includes(k)})}).length;var ex=/2 anos|3 anos|2 anos e|1 ano e [1-9]/.test(c.experiencia)?90:75;var fo=/Técnico em Administração/.test(c.formacao)?95:/Tecnólogo/.test(c.formacao)?90:75;var hs=Math.min(100,hm/4*100),ss=Math.min(100,sm/4*100);return Math.round(hs*.30+ss*.30+ex*.20+fo*.10+c.entrevista*.10)}
function card(c){return "<article class='candidate "+(S.tri.includes(c.id)?"selected":"")+"'><img class='candidate-photo' src='assets/candidatos/"+encodeURIComponent(c.foto||"")+"' alt='Foto ilustrativa de "+esc(c.nome)+"' loading='lazy' onerror='this.style.display=\"none\"'><div class='avatar'>"+c.nome.split(" ").slice(0,2).map(function(x){return x[0]}).join("")+"</div><div class='candidate-id'>"+c.id+"</div><b>"+esc(c.nome)+"</b><p>"+esc(c.formacao)+"</p><p>"+esc(c.experiencia)+"</p><p>"+c.hard.slice(0,3).map(function(x){return "<span class='tag'>"+esc(x)+"</span>"}).join("")+"</p><details><summary>Ver ficha completa</summary><p><b>Hard skills:</b> "+c.hard.map(esc).join(", ")+"</p><p><b>Soft skills:</b> "+c.soft.map(esc).join(", ")+"</p><p><b>Teste:</b> "+c.teste+"/100 • <b>Entrevista:</b> "+c.entrevista+"/100</p><p><b>Pretensão:</b> R$ "+c.pretensao+" • <b>Disponibilidade:</b> "+esc(c.disponibilidade)+"</p><p><b>Desenvolvimento:</b> "+esc(c.desenvolvimento)+"</p></details><button onclick='tri(\""+c.id+"\")'>"+(S.tri.includes(c.id)?"Retirar":"Selecionar")+"</button></article>"}
const views=[
function(){return ""},
function(){return "<section class='card'><small>MISSÃO</small><h1>Processo seletivo: Assistente Administrativo</h1><p>A Nova Gestão Serviços Administrativos Ltda. (fictícia) precisa contratar um profissional para apoiar documentos, atendimento, planilhas e controles internos.</p><div class='notice'><b>Requisitos:</b> ensino médio, informática básica, organização, comunicação e trabalho em equipe.<br><b>Diferenciais:</b> Excel intermediário, experiência administrativa, ERP e indicadores.</div><h2>Seu papel</h2><p>Você será responsável por tomar decisões em diferentes etapas. Suas escolhas serão analisadas pelo processo, não apenas pelo resultado final.</p><button onclick='go(2)'>Começar recrutamento</button></section>"},
function(){return "<section class='card'><h1>Etapa 2 — Recrutamento</h1><p>Antes de analisar currículos, responda às questões sobre recrutamento e seleção.</p>"+questionBlock("recrutamento")+"<button onclick='finishRecruitment()'>Continuar</button></section>"},
function(){return "<section class='card'><h1>Etapa 3 — Triagem curricular</h1><p>Analise os 30 perfis e selecione até <b>8 candidatos</b> para a próxima etapa. A fotografia é apenas identificação visual; utilize as informações profissionais.</p><div class='grid'>"+S.c.map(card).join("")+"</div><p><b>"+S.tri.length+"/8 selecionados</b></p><button onclick='go(4)' "+(S.tri.length<3?"disabled":"")+">Continuar para CHA</button></section>"},
function(){return "<section class='card'><h1>Etapa 4 — Modelo CHA</h1><p>Associe competências técnicas e socioemocionais aos candidatos selecionados. Depois responda ao miniquestionário.</p>"+S.tri.map(function(id){let c=S.c.find(function(x){return x.id===id});return "<div class='notice'><b>"+c.nome+"</b><label>Hard skill<select onchange=\"setcha('"+id+"','h',this.value)\"><option value=''>Selecione</option>"+c.hard.map(function(x){return "<option>"+esc(x)+"</option>"}).join("")+"</select></label><label>Soft skill<select onchange=\"setcha('"+id+"','s',this.value)\"><option value=''>Selecione</option>"+c.soft.map(function(x){return "<option>"+esc(x)+"</option>"}).join("")+"</select></label></div>"}).join("")+"<h2>Verificação</h2>"+questionBlock("cha")+"<button onclick='finishCHA()'>Continuar para teste</button></section>"},
function(){return "<section class='card'><h1>Etapa 5 — Teste técnico</h1><p>Resolva as situações práticas. Aqui, conhecimento técnico e comportamento aparecem juntos, mas devem ser distinguidos.</p><div class='quiz'>"+testBank.map(function(q,i){return "<div class='notice'><b>"+q.q+"</b>"+q.opts.map(function(o,j){return "<label><input type='radio' name='teste"+i+"' value='"+j+"'> "+o+"</label>"}).join("")+"</div>"}).join("")+"</div><button onclick='finishTest()'>Ver resultados e entrevistas</button></section>"},
function(){return "<section class='card'><h1>Etapa 6 — Entrevista</h1><p>Você recebeu os resultados das etapas anteriores. Compare evidências, mas não reduza a seleção a um único indicador.</p><table><tr><th>Candidato</th><th>Teste</th><th>Entrevista</th><th>Desenvolvimento</th></tr>"+S.tri.map(function(id){let c=S.c.find(function(x){return x.id===id});return "<tr><td>"+esc(c.nome)+"</td><td>"+c.teste+"/100</td><td>"+c.entrevista+"/100</td><td>"+esc(c.desenvolvimento)+"</td></tr>"}).join("")+"</table><h3>Pergunta de análise</h3><p>Qual evidência deve receber maior atenção na comparação final?</p><select id='evidence'><option value=''>Selecione</option><option value='technical'>Resultado técnico relacionado à vaga</option><option value='soft'>Competências socioemocionais observadas</option><option value='experience'>Experiência anterior</option><option value='single'>Apenas o maior número de uma etapa</option></select><br><br><button onclick='finishInterview()'>Ir para decisão</button></section>"},
function(){return "<section class='card'><h1>Etapa 7 — Decisão final</h1><p>Escolha até 3 finalistas e indique quem seria contratado. Depois justifique com evidências.</p><div class='grid'>"+S.tri.map(function(id){let c=S.c.find(function(x){return x.id===id});return "<article class='candidate "+(S.final.includes(id)?"selected":"")+"'><img class='candidate-photo small' src='assets/candidatos/"+encodeURIComponent(c.foto||"")+"' alt='Foto ilustrativa de "+esc(c.nome)+"' loading='lazy' onerror='this.style.display=\"none\"'><b>"+esc(c.nome)+"</b><p>Teste: "+c.teste+" • Entrevista: "+c.entrevista+"</p><button onclick=\"fin('"+id+"')\">"+(S.final.includes(id)?"Retirar":"Finalista")+"</button></article>"}).join("")+"</div><label>Contratado<select id='hire'><option value=''>Selecione</option>"+S.final.map(function(id){let c=S.c.find(function(x){return x.id===id});return "<option value='"+id+"'>"+esc(c.nome)+"</option>"}).join("")+"</select></label><label>Justificativa<textarea id='why' rows='5' placeholder='Explique quais competências, resultados e evidências sustentam sua escolha.'></textarea></label><button onclick='decision()'>Confirmar decisão</button></section>"},
function(){let c=S.c.find(function(x){return x.id===S.hire});return "<section class='card'><h1>Etapa 8 — Treinamento e desenvolvimento</h1><div class='notice'><b>"+esc(c.nome)+"</b><br>Necessidade identificada: "+esc(c.desenvolvimento)+"</div><p>Escolha a modalidade mais adequada e responda ao bloco de desenvolvimento.</p><div class='grid'>"+["Presencial","Online","Híbrido","Prático no trabalho"].map(function(x){return "<button onclick=\"train('"+x+"')\">"+x+"</button>"}).join("")+"</div>"+questionBlock("desenvolvimento")+"<br><button onclick='finishDevelopment()'>Concluir processo</button></section>"},
function(){let c=S.c.find(function(x){return x.id===S.hire});let filled=Object.values(S.cha).filter(function(x){return x.h&&x.s}).length;let scores=calcScores();let chosenFit=fit(c);let allSorted=S.c.slice().sort(function(a,b){return fit(b)-fit(a)});let best=allSorted[0];let rank=allSorted.findIndex(function(x){return x.id===c.id})+1;let feedback=scores.d1>=70?"Você identificou conceitos centrais do recrutamento e seleção.":"Revise a diferença entre recrutamento, seleção e instrumentos de avaliação.";let feedback2=scores.d2>=70?"Você conseguiu relacionar competências técnicas e socioemocionais às evidências.":"Revise a distinção entre hard skills e soft skills e observe as evidências antes de decidir.";let feedback3=scores.d3>=70?"Você relacionou necessidade de desenvolvimento e modalidade de treinamento.":"Revise a relação entre lacuna de competência, necessidade de treinamento e modalidade.";return "<section class='card'><small>DEVOLUTIVA PEDAGÓGICA</small><h1>Processo concluído</h1><p><b>Participante:</b> "+esc(S.student)+" • <b>Turma:</b> "+esc(S.turma)+"</p><div class='grid'><div class='notice'><div class='score'>"+scores.d1+"%</div><b>Descritor 1</b><br>Recrutamento e seleção</div><div class='notice'><div class='score'>"+scores.d2+"%</div><b>Descritor 2</b><br>CHA</div><div class='notice'><div class='score'>"+scores.d3+"%</div><b>Descritor 3</b><br>Treinamento e desenvolvimento</div></div><h2>Decisão registrada</h2><p><b>"+esc(c.nome)+"</b></p><p>Treinamento: <b>"+esc(S.train)+"</b></p><h3>Feedback</h3><div class='notice'>"+feedback+"<br><br>"+feedback2+"<br><br>"+feedback3+"</div><p><b>Triagem:</b> "+S.tri.length+" • <b>CHA preenchido:</b> "+filled+"/"+S.tri.length+"</p><div class='notice'><b>Compatibilidade objetiva:</b> "+chosenFit+"/100.<br>O perfil com maior alinhamento aos critérios técnicos da vaga foi <b>"+esc(best.nome)+"</b> ("+fit(best)+"/100). Sua escolha ficou na posição <b>"+rank+"ª</b> pela matriz. Isso não substitui sua justificativa: explique a decisão usando evidências do processo.</div><button onclick='exportResult()'>Baixar relatório</button> <button onclick='location.reload()'>Nova simulação</button></section>"}
];
function go(n){S.step=n;render()}
function tri(id){if(S.tri.includes(id))S.tri=S.tri.filter(function(x){return x!==id});else if(S.tri.length<8)S.tri.push(id);render()}
function setcha(id,k,v){if(!S.cha[id])S.cha[id]={};S.cha[id][k]=v}
function fin(id){if(S.final.includes(id))S.final=S.final.filter(function(x){return x!==id});else if(S.final.length<3)S.final.push(id);render()}
function finishRecruitment(){S.answers.recrutamento={ok:gradeGroup("recrutamento")};go(3)}
function finishCHA(){S.answers.chaQuiz={ok:gradeGroup("cha")};go(5)}
function finishTest(){let ok=0;testBank.forEach(function(q,i){let el=document.querySelector("input[name='teste"+i+"']:checked");if(el&&Number(el.value)===q.a)ok++});S.answers.teste={ok:ok,total:testBank.length};go(6)}
function finishInterview(){S.answers.evidence=document.querySelector("#evidence").value;go(7)}
function decision(){S.hire=document.querySelector("#hire").value;S.why=document.querySelector("#why").value;if(!S.hire)return alert("Selecione o contratado.");go(8)}
function train(x){S.train=x}
function finishDevelopment(){if(!S.train)return alert("Escolha uma modalidade de treinamento.");S.answers.desenvolvimentoQuiz={ok:gradeGroup("desenvolvimento")};go(9)}
function calcScores(){let r=(S.answers.recrutamento?.ok||0)/3*40;let selected=S.tri.map(function(id){return S.c.find(function(x){return x.id===id})}).filter(Boolean);let triFit=selected.length?selected.reduce(function(sum,c){return sum+fit(c)},0)/selected.length/100*40:0;let evidence=(S.answers.evidence==="technical"||S.answers.evidence==="soft")?20:0;let d1=Math.round(r+triFit+evidence);
let cq=(S.answers.chaQuiz?.ok||0)/3*30;let filled=Object.values(S.cha).filter(function(x){return x.h&&x.s}).length;let cha=selected.length?filled/selected.length*20:0;let tq=(S.answers.teste?.ok||0)/testBank.length*30;let d2=Math.round(cq+cha+tq+20);
let dq=(S.answers.desenvolvimentoQuiz?.ok||0)/3*50;let c=S.c.find(function(x){return x.id===S.hire});let need=(c&&c.desenvolvimento||"").toLowerCase();let practical=/(comunicação|atendimento|reuniões|publico|público)/.test(need);let technical=/(excel|erp|sistemas|processos|indicadores|rotinas|relatórios|relatorios)/.test(need);let train=(practical&&(S.train==="Prático no trabalho"||S.train==="Presencial"||S.train==="Híbrido"))||(technical&&(S.train==="Online"||S.train==="Híbrido"||S.train==="Prático no trabalho"))?30:18;let d3=Math.round(dq+train+20);return{d1:Math.min(100,d1),d2:Math.min(100,d2),d3:Math.min(100,d3)}}
function exportResult(){let out={participante:S.student,turma:S.turma,triagem:S.tri,finalistas:S.final,contratado:S.hire,treinamento:S.train,justificativa:S.why,respostas:S.answers,pontuacao:calcScores(),compatibilidade:fit(S.c.find(function(x){return x.id===S.hire})),data:new Date().toISOString()};let blob=new Blob([JSON.stringify(out,null,2)],{type:"application/json"});let a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="relatorio-"+S.student.replace(/\\s+/g,"-")+".json";a.click();URL.revokeObjectURL(a.href)}
boot();